/********************************************************************************
 * Copyright (c) 2026 Fraunhofer ISE
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 ********************************************************************************/

rootProject.name = 'ship-root'

include 'ship'
project(':ship').projectDir = new File(settingsDir, 'projects/ship')

include 'ship-cli'
project(':ship-cli').projectDir = new File(settingsDir, 'projects/ship-cli')

include 'demo'
project(':demo').projectDir = new File(settingsDir, 'projects/demo')

